<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Version>1.0.0</Version>
		<AssemblyName>Huge.MovLit.Shared.Oqtane</AssemblyName>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
	</PropertyGroup>

	<ItemGroup>
		<!-- Re-added BlogPost.cs to compilation -->
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Oqtane.Shared" Version="6.2.1" />
		<!-- Fundamental Blazor packages -->
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.9" />
	</ItemGroup>

</Project>
